name: CI Backend - Docker Build

on:
  push:
    branches: [master]
    workflow_dispatch:
    paths:
      - 'ChatApp/**'
      - '!AppChat/**'
  pull_request:
    branches: [master]
     workflow_dispatch:
    paths:
      - 'ChatApp/**'
      - '!AppChat/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - run: docker build -t chatapp-backend ./ChatApp
