name: CI Fullstack - Docker Compose (Dev Test)

on:
  push:
    branches: [devv]
    paths:
      - 'AppChat/**'
      - 'ChatApp/**'
      - 'docker-compose.yml'

  pull_request:
    branches: [devv]
    paths:
      - 'AppChat/**'
      - 'ChatApp/**'
      - 'docker-compose.yml'

jobs:
  build-fullstack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose services (frontend + backend)
        run: docker compose -f docker-compose.yml build
